---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: mydeployment
spec:
  replicas: 5
  selector:
     matchLabels:
       app: myrep
  template:
    metadata:
      labels:
        app: myrep
    spec:
       containers:
       - name: httpd
         image: httpd
         ports:
            - containerPort: 80
         imagePullPolicy: Always
