---
apiVersion: v1
kind: Pod
metadata: 
   name: mypod
   labels: 
     app: web
spec: 
   containers: 
     - name: httpd
       image: httpd
       ports: 
          - containerPort: 8080
       imagePullPolicy: Always
     - name: nginx
       image: nginx
       ports: 
          - containerPort: 8080

     
